# Site settings 
title: John Mark Agosta's musings
email: johnmark.agosta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Occasional notes on current readings, theory, language & (gasp) culture
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnmarkagosta.com" # the base hostname & protocol for your site
twitter_username: quantifiedcar
github_username:  jmagosta

# Build settings
markdown: kramdown
